Feature/tk17 develop score controller component ongoing challenge screen duel
MarinaFX/Fiero pull request #119
Opened 2022-08-04 20:12 UTC by jgabrielbiazus

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Developed Score component (Duel)
> - Step 2: Create groups for the Score Component (group)

# Description 📝
## Project Info 📈
> - US **03**
> - Task 
>   - ID: **13**
>   - Title: **Develop Front-end Score Controller Component of Ongoing Challenge Screen (Duel)**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

<img width="322" alt="Screen Shot 2022-08-04 at 16 51 58" src="https://user-images.githubusercontent.com/69223192/182943726-0655e771-5a67-4fdc-80be-3371ee9d78ec.png">

**Additional context** 🌎
Add any other context about the problem here.

2022-08-08 17:40 UTC, MarinaFX requested changes

2022-08-08 17:40 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> -				DEVELOPMENT_TEAM = GYMDP69744;
quando comitar alteracoes, nao alterar o development team. 
Ja deu conflitos em PRs anteriores, vamos manter sempre no mesmo quando subir as alterações

2022-08-08 17:40 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = KY3S643HND;
mesma coisa aqui

2022-08-09 17:22 UTC, illuminatyy approved these changes

2022-08-10 17:44 UTC, MarinaFX commented
Implemented at #122

2022-08-10 17:44 UTC, closed without merging