Create Profile Picture Component
MarinaFX/Fiero pull request #165
Opened 2022-08-18 19:13 UTC by MarceloDiefenbach

# What was done? ✅
 Describe in a few words what have you done? 
 - Step 1: Create a folder of Profile Picture Component inside DesignSystem/Component folder
 - Step 2: Implement the component that show user image and name
 - Step 3: Develop TabBar with challenge list and profile tabs
 - Step 4: after develop TabBar, i do some changes to navigations work (challenge details screen and first screen of create  
 - Step 5: quick challenge. Now this screens open as sheet withou dismiss action.
 - Step 6: Develop back button on challenge details screen
 - Step 7: develop profile component
 - Step 8: devolop profile screen with button to delete account  (TODO: in viewmodel do logic to delete account
 - Step 9: fix color of background on challenge detail screen
 - Step 10: Develop alert to confirm account delete (delete account)
 - Step 11: develop alert of server error (delete account)

# Description 📝
## Project Info 📈
 - US **08**
 - Task 
   - ID: **15**
   - Title: **Develop User Profile Picture Component**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
<img src="https://user-images.githubusercontent.com/58398373/185475415-0530b6e2-151a-4c47-9f01-1dad1e27c2b5.png" alt="Screenshot of login screen" width=414 >

2022-08-19 17:57 UTC, jgabrielbiazus approved these changes

2022-08-22 16:45 UTC, MarinaFX requested changes

2022-08-22 16:45 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 6525BU9D84;
mudar development team

2022-08-22 16:45 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.pazzi.marina.FieroApp4;
mudar development team

2022-08-22 16:45 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 6525BU9D84;
mudar development team

2022-08-22 16:45 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.pazzi.marina.FieroApp4;
voltar package anterior

2022-08-22 16:45 UTC, MarinaFX commented on Fiero.xcodeproj/xcuserdata/marcelodiefenbach.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +</Bucket>
nao subir esse arquivo

2022-08-22 16:45 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
> +        NavigationView{
talvez seria melhor tirar essa navigation view, senao vamos ter 2

2022-08-22 17:19 UTC, merged