Implement long press count
MarinaFX/Fiero pull request #166
Opened 2022-08-18 19:37 UTC by jgabrielbiazus

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Implemented on Duel Score Component long press count
> - Step 2: Implemented on Score Component 3-4 long press count

# Description 📝
## Project Info 📈
> - US **06**
> - Task 
>   - ID: **14**
>   - Title: **Develop Long Press Gesture When Increasing And Decreasing Player Points**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱

https://user-images.githubusercontent.com/69223192/185479608-3dc019ab-fff3-4bdf-a051-e70a8c80b170.mp4

**Additional context** 🌎
Add any other context about the problem here.

2022-08-22 17:29 UTC, MarinaFX requested changes

2022-08-22 17:29 UTC, MarinaFX commented on Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
> +//                }
remover codigo comentado

2022-08-22 17:29 UTC, MarinaFX commented on Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
> +//                }
remover codigo comentado

2022-08-23 20:00 UTC, illuminatyy approved these changes

2022-08-29 22:57 UTC, merged