Feature/TK1 Develop Online or Offline Type Challenge View
MarinaFX/Fiero pull request #328
Opened 2022-10-21 17:29 UTC by illuminatyy

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Created a card(`OnlineOrOfflineCard.swift`) and enum style(`OnlineOrOfflineStyles.swift`) for Online or Offline TabBar
> - Step 2: Implemented `OnlineOrOfflineView.swift`
> - Step 3: Changed the percentage of `CustomProgressBar.swift` (added a new screen, so the percentage needed to be modified)

# Description 📝
## Project Info 📈
> - US **21**
> - Task 
>   - ID: **1**
>   - Title: **Develop Online or Offline Type Challenge View**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
Portuguese: 
https://user-images.githubusercontent.com/51174686/197252531-6f965b04-0cf4-4736-b7d6-0556a3bdc19c.mp4

English:
https://user-images.githubusercontent.com/51174686/197252369-37fc4ab3-4ee1-4f69-bfef-608309e59a7b.mp4

2022-10-24 18:38 UTC, MarinaFX requested changes

2022-10-24 18:38 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineCard.swift
> +struct OnlineOrOfflineCard: View {
apesar do nome nao ser muito genérico, ja existe um componente pra esse card

`ChallengeParticipantsSelectionCardView.swift`

2022-10-24 18:38 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
> +                switch tabViewSelection {
sugestao: talvez ao inves de um switch da tabview, poderia usar um ternário no texto

```swift
ButtonComponent(style: .secondary(isEnabled: true), text: tabViewSelection == 1 ? "Online!" : "Offline!") {
     pushNextView.toggle()
}
```

assim da pra reduzir as linhas de codigos duplicadas

2022-10-24 18:38 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineCard.swift
> +struct OnlineOrOfflineCard: View {
alias, se ja quiser pode renomear tbm esse arquivo, mas como os dois em tese sao idênticos a gente precisa escolher um pra poder manter e reusar

2022-10-24 19:35 UTC, jgabrielbiazus submitted a review, later dismissed

2022-10-25 17:55 UTC, illuminatyy commented on Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineCard.swift
> +struct OnlineOrOfflineCard: View {
fiz as alterações!

2022-10-25 18:00 UTC, illuminatyy commented on Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
> +                switch tabViewSelection {
Eu tentei alterar, mas não atualizava o text do botão. Então achei melhor deixar do jeito que funciona por enquanto

2022-10-25 18:35 UTC, MarinaFX submitted a review, later dismissed

2022-10-25 18:35 UTC, MarinaFX commented
resolvendo os conflitos, LGTM

2022-10-25 18:41 UTC, merged