Feature/TK 31 Develop Enter In Challenge By Invitation Code View
MarinaFX/Fiero pull request #329
Opened 2022-10-21 19:25 UTC by illuminatyy

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Implemented Enter with Code screen (`EnterWithCode.swift`)
> - Step 2: Localized `EnterWithCode.swift`

# Description 📝
## Project Info 📈
> - US **24**
> - Task 
>   - ID: **31**
>   - Title: **Develop Enter In Challenge By Invitation Code View**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
Portuguese:
<img width="230" alt="Enter with code Portuguese screen on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197272522-f0117430-c922-4bf0-9226-cedba16a078b.png">
<img width="230" alt="Enter with code Portuguese screen with keyboard on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197272574-77f109a2-ab97-4667-8c5d-e96bf62c8272.png">

English:
<img width="230" alt="Enter with code English screen on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197272613-35ceac4a-acd6-45ab-b30a-b7c208030923.png">
<img width="230" alt="Enter with code English screen with keyboard on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197272649-511bae0c-b714-4370-901f-dfaada66adbd.png">

2022-10-24 18:43 UTC, MarinaFX requested changes

2022-10-24 18:43 UTC, MarinaFX commented on Fiero.xcodeproj/project.pbxproj
> +		CCE03FED290318280038737A /* EnterWithCode.swift in Sources */ = {isa = PBXBuildFile; fileRef = CCE03FEC290318280038737A /* EnterWithCode.swift */; };
renomear aquivo para: `EnterWithCodeView`

toc para seguir nomenclaturas

2022-10-25 18:05 UTC, illuminatyy commented on Fiero.xcodeproj/project.pbxproj
> +		CCE03FED290318280038737A /* EnterWithCode.swift in Sources */ = {isa = PBXBuildFile; fileRef = CCE03FEC290318280038737A /* EnterWithCode.swift */; };
feito!

2022-10-25 18:07 UTC, MarinaFX approved these changes

2022-10-25 18:07 UTC, merged