Feature/TK 14 Develop Invitation Code View
MarinaFX/Fiero pull request #331
Opened 2022-10-21 20:46 UTC by illuminatyy

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Implemented Invitation Code View (`InviteChallenger.swift`)
> - Step 2: Localized `InviteChallenger.swift `

# Description 📝
## Project Info 📈
> - US **23**
> - Task 
>   - ID: **14**
>   - Title: **Develop Invitation Code View**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
Portuguese:
<img width="230" alt="Invite challenger Portuguese screen on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197285237-a0cc14c8-e10a-4e99-85e5-4a452b659ceb.png">
English:
<img width="230" alt="Invite challenger English screen on Iphone 14 pro max simulator" src="https://user-images.githubusercontent.com/51174686/197285308-ca1fe296-5b25-4743-9df7-675e4bf5daf1.png">

2022-10-24 18:52 UTC, MarinaFX requested changes

2022-10-24 18:52 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
> +                        print("código copiado")
faltou implementar a função de copiar o codigo

acho que da pra fazer da seguinte forma: 
1. cria uma função - ex: copyInviteCodeAction (sem parâmetros e sem retornos)
2. dentro da função: 

```swift
func copyInviteCodeAction() {
     UIPasteboard.general.string = self.inviteCode
}
```

3. chamar essa função na action

```swift
Button(action: copyInviteCodeAction, 
label: {
   ...
}
```

2022-10-25 18:15 UTC, illuminatyy commented on Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
> +                        print("código copiado")
Feito! Viajei de não ter feito isso 🫠

2022-10-25 18:23 UTC, MarinaFX approved these changes

2022-10-25 18:23 UTC, merged