Feature/TK 5: Develop Front-end Integration for Online or Offline Screen Flow
MarinaFX/Fiero pull request #337
Opened 2022-10-26 19:49 UTC by illuminatyy

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Created an `@State var isOnline` to passthrough the online state(boolean) in all pages/steps of creation
> - Step 2: Added the new variable on Navigation links
> - Step 3: Added on call to server the `isOnline` state on `QCAmountWinRulesView.swift` button "Criar desafio"
> - Step 4: Changed the `var invitationCode` for optional in `QuickChallenge.swift` model
> - Step 5: Fixed `enum ErrorState var description` to return a `LocalizedStringKey` and modified localizables files to change the alert error titles in English

# Description 📝
## Project Info 📈
> - US **21**
> - Task 
>   - ID: **5**
>   - Title: **Develop Front-end Integration for Online or Offline Screen Flow**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
- Online Flow:
https://user-images.githubusercontent.com/51174686/198120553-080497e8-1d38-48c4-97d4-6599b2223b02.mp4
<img width="400" alt="Captura de Tela 2022-10-26 às 00 26 19" src="https://user-images.githubusercontent.com/51174686/198120599-3dfa8456-f0de-49e6-96d4-a08d1e0331de.png">

- Offline Flow:
https://user-images.githubusercontent.com/51174686/198120662-258ea4b7-51c0-4be5-8575-8eec1a1bd176.mp4
<img width="400" alt="Captura de Tela 2022-10-26 às 00 27 54" src="https://user-images.githubusercontent.com/51174686/198120728-05333bc7-b3f6-4622-8fe2-c9084a999133.png">

2022-10-26 20:26 UTC, MarinaFX requested changes

2022-10-26 20:26 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/QCNamingView.swift
> +    @State var isOnline: Bool
Como nao vamos mais mudar o estado desse booleano (nao vamos alterar na tela de nome do desafio se ele eh online ou offline), ele pode ser uma var normal. 

Ele sendo declarado como `@State` aqui, acaba criando duas fontes da verdade (o state da tela anterior e o de agora), e mais pra frente pode nos dar problema de referencias

2022-10-26 20:26 UTC, MarinaFX commented on Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
> +    @State var isOnline: Bool
aqui tbm

2022-10-26 21:04 UTC, illuminatyy commented on Fiero/Views/Challenges/Quick/QCNamingView.swift
> +    @State var isOnline: Bool
feito!

2022-10-26 21:04 UTC, illuminatyy commented on Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
> +    @State var isOnline: Bool
feito tbm

2022-10-27 17:14 UTC, MarinaFX approved these changes

2022-10-27 17:14 UTC, merged