Improvement/TK23 Develop Support to Dynamic Types on Registration Screen
MarinaFX/Fiero pull request #82
Opened 2022-07-15 17:07 UTC by illuminatyy

# What was done? ✅
> Describe in a few words what have you done? 
> - Step 1: Created a `@Environment(\.sizeCategory) `  to show a scroll view when dynamic types was used
> - Step 2: Hidded the `navigation bar` (adjusted content on the middle of the screen)
> - Step 3: Created a var to organized Tokens Spacing on `TermsOfUseSheetScreen.swift`

# Description 📝
## Project Info 📈
> - US **01**
> - Task 
>   - ID: **23**
>   - Title: **Develop Support to Dynamic Types on Registration Screen**
  
# Evidence 🕵️‍♀️
## **Screenshots/Videos/Figma** 📱
> - IOS 15 (iPhone 13 Pro Max & iPod touch):
https://user-images.githubusercontent.com/51174686/179272598-c784ae81-a571-4952-beb2-e07d3bc2bffb.mp4
https://user-images.githubusercontent.com/51174686/179272811-066282ba-be5f-4969-a7cd-f90163cfa2fa.mp4
> - IOS 14 (iPhone 11 Pro Max & iPod touch):
https://user-images.githubusercontent.com/51174686/179273104-9f6ae0ce-e47a-4d8c-b4af-1bef3f11f36a.mp4
https://user-images.githubusercontent.com/51174686/179273198-cc536453-e1c7-4869-b89f-f0885995dcab.mp4

2022-07-15 19:49 UTC, jgabrielbiazus approved these changes

2022-07-15 20:03 UTC, MarinaFX approved these changes

2022-07-15 20:11 UTC, MarinaFX requested changes
so remover o codigo comentado ali e tudo top

2022-07-15 20:11 UTC, MarinaFX commented on Fiero/Views/Login/RegistrationScreenView.swift
> +                        //.resizable()
remover codigo comentado

2022-07-17 23:17 UTC, illuminatyy commented on Fiero/Views/Login/RegistrationScreenView.swift
> +                        //.resizable()
Feito!!

2022-07-18 16:12 UTC, MarinaFX approved these changes
approved

2022-07-18 16:12 UTC, merged